# Generated by Django 6.0.7 on 2026-07-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(choices=[('Sahih Bukhari', 'Sahih Al-Bukhari'), ('Sahih Muslim', 'Sahih Muslim'), ("Sunan An-Nasa'i", "Sunan An-Nasa'i"), ('Sunan Abu Dawud', 'Sunan Abu Dawud'), ('Jami` At-Tirmidhi', 'Jami` At-Tirmidhi'), ('Sunan Ibn Majah', 'Sunan Ibn Majah'), ('Riyad As-Salihin', 'Riyad As-Salihin')], default='Sahih Bukhari', max_length=100)),
                ('chapter', models.CharField(blank=True, max_length=255)),
                ('hadith_number', models.PositiveIntegerField()),
                ('arabic_text', models.TextField()),
                ('translation', models.TextField()),
                ('narrated_by', models.CharField(blank=True, max_length=150)),
                ('grade', models.CharField(default='Sahih', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hadiths',
                'ordering': ['book_name', 'hadith_number'],
            },
        ),
        migrations.CreateModel(
            name='QuranAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveIntegerField()),
                ('surah_name_arabic', models.CharField(max_length=100)),
                ('surah_name_english', models.CharField(max_length=100)),
                ('reciter', models.CharField(default='Mishary Rashid Alafasy', max_length=150)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_url', models.URLField(blank=True, help_text='Direct MP3 Audio Stream URL if no file uploaded', max_length=500)),
                ('duration', models.CharField(blank=True, default='00:00', max_length=20)),
                ('revelation_place', models.CharField(choices=[('Makki', 'Makki'), ('Madani', 'Madani')], default='Makki', max_length=50)),
                ('total_ayahs', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quran Audio',
                'verbose_name_plural': 'Quran Audios',
                'ordering': ['surah_number'],
            },
        ),
        migrations.CreateModel(
            name='Tafseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveIntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('ayah_number', models.PositiveIntegerField()),
                ('arabic_text', models.TextField()),
                ('translation', models.TextField()),
                ('tafseer_text', models.TextField()),
                ('scholar_name', models.CharField(default='Tafseer Ibn Kathir', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tafseers',
                'ordering': ['surah_number', 'ayah_number'],
            },
        ),
        migrations.CreateModel(
            name='BookMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='Unknown Author', max_length=150)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('pdf_url', models.URLField(blank=True, help_text='Direct PDF document URL', max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('pages_count', models.PositiveIntegerField(blank=True, default=100)),
                ('language', models.CharField(default='Arabic / English', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='core.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(default='Islamic Scholar', max_length=150)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube Embed or Direct Video URL', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
