# Generated by Django 5.2.16 on 2026-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmedia',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document (.docx)'), ('ppt', 'PPT Presentation (.pptx)'), ('book', 'Printed / E-Book')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Direct Document URL', max_length=500),
        ),
    ]
