# Generated by Django 5.2.16 on 2026-07-26 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookmedia_file_type_alter_bookmedia_pdf_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedia',
            name='pages_count',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.CreateModel(
            name='AyahReflectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveIntegerField()),
                ('ayah_number', models.PositiveIntegerField()),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayah_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfilePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_qari', models.CharField(default='ar.alafasy', max_length=100)),
                ('preferred_language', models.CharField(default='ur', max_length=20)),
                ('preferred_font_size', models.PositiveIntegerField(default=28)),
                ('preferred_theme', models.CharField(default='light', max_length=20)),
                ('location_city', models.CharField(blank=True, default='Karachi', max_length=100)),
                ('last_read_surah', models.PositiveIntegerField(default=1)),
                ('last_read_ayah', models.PositiveIntegerField(default=1)),
                ('khatm_target_days', models.PositiveIntegerField(default=30)),
                ('completed_surahs_json', models.TextField(default='[]')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZakatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('zakat_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='DailyPrayerTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fajr', models.BooleanField(default=False)),
                ('dhuhr', models.BooleanField(default=False)),
                ('asr', models.BooleanField(default=False)),
                ('maghrib', models.BooleanField(default=False)),
                ('isha', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namaz_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
