# Generated by Django 6.0.7 on 2026-07-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bookmedia_pages_count_ayahreflectionnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaqreerAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(default='Islamic Scholar', max_length=150)),
                ('language', models.CharField(choices=[('arabic', 'Arabic (عربي)'), ('brahui', 'Brahui (براہوئی)'), ('urdu', 'Urdu (اردو)')], default='urdu', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='taqreer_audio/')),
                ('audio_url', models.URLField(blank=True, help_text='Direct MP3 Audio URL', max_length=500)),
                ('duration', models.CharField(blank=True, default='00:00', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taqreers', to='core.category')),
            ],
            options={
                'verbose_name': 'Taqreer Audio',
                'verbose_name_plural': 'Taqreer Audios',
                'ordering': ['-created_at'],
            },
        ),
    ]
