# Generated by Django 5.2.16 on 2026-07-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taqreeraudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedia',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document (.docx)'), ('ppt', 'PPT Presentation (.pptx)'), ('book', 'Printed / E-Book')], db_index=True, default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='book_name',
            field=models.CharField(choices=[('Sahih Bukhari', 'Sahih Al-Bukhari'), ('Sahih Muslim', 'Sahih Muslim'), ("Sunan An-Nasa'i", "Sunan An-Nasa'i"), ('Sunan Abu Dawud', 'Sunan Abu Dawud'), ('Jami` At-Tirmidhi', 'Jami` At-Tirmidhi'), ('Sunan Ibn Majah', 'Sunan Ibn Majah'), ('Riyad As-Salihin', 'Riyad As-Salihin')], db_index=True, default='Sahih Bukhari', max_length=100),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='grade',
            field=models.CharField(db_index=True, default='Sahih', max_length=50),
        ),
        migrations.AlterField(
            model_name='quranaudio',
            name='reciter',
            field=models.CharField(db_index=True, default='Mishary Rashid Alafasy', max_length=150),
        ),
        migrations.AlterField(
            model_name='quranaudio',
            name='surah_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tafseer',
            name='scholar_name',
            field=models.CharField(db_index=True, default='Tafseer Ibn Kathir', max_length=150),
        ),
        migrations.AlterField(
            model_name='tafseer',
            name='surah_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taqreeraudio',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic (عربي)'), ('brahui', 'Brahui (براہوئی)'), ('urdu', 'Urdu (اردو)')], db_index=True, default='urdu', max_length=20),
        ),
    ]
