# Generated by Django 5.2.16 on 2026-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bookmedia_file_type_alter_hadith_book_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quranaudio',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic Recitation (تلاوت)'), ('brahui', 'Brahui Translation MP3 (براہوئی ترجمہ)'), ('urdu', 'Urdu Translation MP3 (اردو ترجمہ)')], db_index=True, default='arabic', max_length=20),
        ),
    ]
