# Generated by Django 6.0.7 on 2026-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quranaudio_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedia',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('ar', 'Arabic'), ('br', 'Brahui')], db_index=True, default='ur', max_length=2),
        ),
    ]
