# Generated by Django 6.0.7 on 2026-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bookmedia_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedia',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu (اردو)'), ('ar', 'Arabic (عربي)'), ('br', 'Brahui (براہوئی)')], db_index=True, default='ur', max_length=20),
        ),
    ]
