# Generated by Django 6.0.7 on 2026-08-08 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_bookmedia_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilepreferences',
            name='achievements_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='reading_history_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='reading_streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='total_ayahs_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document (.docx)'), ('ppt', 'PPT Presentation (.pptx)'), ('book', 'Printed / E-Book'), ('image', 'Image Resource (PNG/JPG/etc.)')], db_index=True, default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='quranaudio',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic Recitation (تلاوت)'), ('brahui', 'Brahui Translation MP3 (براہوئی ترجمہ)'), ('urdu', 'Urdu Translation MP3 (اردو ترجمہ)'), ('english', 'English Translation MP3'), ('sindhi', 'Sindhi Translation MP3 (سنڌي ترجمو)'), ('pashto', 'Pashto Translation MP3 (پښتو ژباړه)'), ('balochi', 'Balochi Translation MP3 (بلوچی گپ)')], db_index=True, default='arabic', max_length=20),
        ),
        migrations.AlterField(
            model_name='taqreeraudio',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic (عربي)'), ('brahui', 'Brahui (براہوئی)'), ('urdu', 'Urdu (اردو)'), ('english', 'English'), ('sindhi', 'Sindhi (سنڌي)'), ('pashto', 'Pashto (پښتو)'), ('balochi', 'Balochi (بلوچی)')], db_index=True, default='urdu', max_length=20),
        ),
        migrations.CreateModel(
            name='AudioPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tracks_json', models.TextField(default='[]', help_text='JSON list of track items: [{id, title, url, type, reciter}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HifzTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.PositiveIntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('memorized', 'Memorized (محفوظ)'), ('in_progress', 'In Progress (جاري Memorization)'), ('revision', 'Needs Revision (مراجعة)'), ('not_started', 'Not Started')], default='not_started', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('last_revised', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surah_number'],
                'unique_together': {('user', 'surah_number')},
            },
        ),
    ]
