# Generated by Django 6.0.7 on 2026-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofilepreferences_achievements_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilepreferences',
            name='avatar',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='dob',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='frame',
            field=models.CharField(blank=True, default='gold', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='quranaudio',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic (عربي)'), ('brahui', 'Brahui Translation MP3 (براہوئی)'), ('urdu', 'Urdu Translation MP3 (اردو)'), ('mixed', 'Mixed Collection (مکسڈ آڈیو)')], db_index=True, default='arabic', max_length=20),
        ),
        migrations.AlterField(
            model_name='taqreeraudio',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic (عربي)'), ('brahui', 'Brahui (براہوئی)'), ('urdu', 'Urdu (اردو)'), ('mixed', 'Mixed Collection (مکسڈ تقارير)')], db_index=True, default='urdu', max_length=20),
        ),
    ]
