# Generated by Django 6.0.7 on 2026-08-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofilepreferences_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilepreferences',
            name='notif_daily_hadith',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='notif_email_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='notif_prayer_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='privacy_profile_visibility',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='privacy_show_activity',
            field=models.BooleanField(default=True),
        ),
    ]
