# Generated by Django 6.0.7 on 2026-08-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dailyquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taqreeraudio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Muhazirah (Lecture)', 'verbose_name_plural': 'Muhazirat (Lectures)'},
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='audio_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='book_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='favorite_recitations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='notif_new_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='notif_system_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='personal_collections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='quran_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='saved_books',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='saved_tafseers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='tafseer_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofilepreferences',
            name='user_notifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='taqreeraudio',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic (عربي)'), ('brahui', 'Brahui (براہوئی)'), ('urdu', 'Urdu (اردو)'), ('mixed', 'Mixed Collection (مکسڈ محاضرات)')], db_index=True, default='urdu', max_length=20),
        ),
    ]
