# Generated by Django 6.0.7 on 2026-09-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_taqreeraudio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('prophets', 'Prophets and Sahaba'), ('hadith', 'Hadith & Sunnah'), ('islam', 'Islam'), ('quran', 'Quran'), ('religion', 'Religion'), ('mix', 'Mix')], db_index=True, default='mix', max_length=50)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Direct Image URL if no file uploaded', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Images Gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
