# Generated by Django 6.0.7 on 2026-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_imagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='taqreeraudio',
            name='arabic_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
