# Generated by Django 6.0.7 on 2026-09-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_taqreeraudio_arabic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quranaudio',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quran_audios', to='core.category'),
        ),
    ]
