# Generated by Django 6.0.7 on 2026-09-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_quranaudio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quranaudio',
            name='tarjuma_qari',
            field=models.CharField(blank=True, help_text='Name of the Tarjuma Qari (e.g., Maulana Muhammad Brahui)', max_length=150),
        ),
    ]
