# Generated by Django 6.0.7 on 2026-09-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_quranaudio_tarjuma_qari'),
    ]

    operations = [
        migrations.AddField(
            model_name='taqreeraudio',
            name='tarjuma_qari',
            field=models.CharField(blank=True, help_text='Name of the Tarjuma Qari / Co-Speaker (Optional)', max_length=150),
        ),
    ]
