# Generated by Django 6.0.7 on 2026-09-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_taqreeraudio_tarjuma_qari'),
    ]

    operations = [
        migrations.AddField(
            model_name='quranaudio',
            name='destination_folder',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='taqreeraudio',
            name='destination_folder',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
